# Generated by Django 5.0.4 on 2024-05-10 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('description', models.TextField()),
                ('authorId', models.IntegerField()),
                ('urlContent', models.CharField(max_length=64)),
                ('datePublished', models.DateTimeField(verbose_name='date published')),
                ('type', models.CharField(max_length=5)),
                ('platformType', models.CharField(max_length=8)),
                ('categories', models.CharField(max_length=10)),
                ('rating', models.IntegerField(default=0)),
                ('isMember', models.BooleanField(default=False)),
            ],
        ),
    ]
